INSERT INTO [dbo].[Customer] ([Id], [UserId], [CompanyName]) VALUES (1, 1, N'BMW Company                                       ')
INSERT INTO [dbo].[Customer] ([Id], [UserId], [CompanyName]) VALUES (2, 1, N'Audi Company                                      ')
INSERT INTO [dbo].[Customer] ([Id], [UserId], [CompanyName]) VALUES (3, 2, N'Ford Company                                      ')
INSERT INTO [dbo].[Customer] ([Id], [UserId], [CompanyName]) VALUES (4, 2, N'Ford Company                                      ')
INSERT INTO [dbo].[Customer] ([Id], [UserId], [CompanyName]) VALUES (5, 3, N'BMW Company                                       ')
